config/routes.rb
Rails.application.routes.draw do
  resources :pokemon_trainers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon_trainer.rb
class PokemonTrainer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_trainers_controller.rb
class PokemonTrainersController < ApplicationController
  before_action :set_pokemon_trainer, only: [:show, :edit, :update, :destroy]

  # GET /pokemon_trainers
  # GET /pokemon_trainers.json
  def index
    @pokemon_trainers = PokemonTrainer.all
  end

  # GET /pokemon_trainers/1
  # GET /pokemon_trainers/1.json
  def show
  end

  # GET /pokemon_trainers/new
  def new
    @pokemon_trainer = PokemonTrainer.new
  end

  # GET /pokemon_trainers/1/edit
  def edit
  end

  # POST /pokemon_trainers
  # POST /pokemon_trainers.json
  def create
    @pokemon_trainer = PokemonTrainer.new(pokemon_trainer_params)

    respond_to do |format|
      if @pokemon_trainer.save
        format.html { redirect_to @pokemon_trainer, notice: 'Pokemon trainer was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon_trainer }
      else
        format.html { render :new }
        format.json { render json: @pokemon_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon_trainers/1
  # PATCH/PUT /pokemon_trainers/1.json
  def update
    respond_to do |format|
      if @pokemon_trainer.update(pokemon_trainer_params)
        format.html { redirect_to @pokemon_trainer, notice: 'Pokemon trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon_trainer }
      else
        format.html { render :edit }
        format.json { render json: @pokemon_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon_trainers/1
  # DELETE /pokemon_trainers/1.json
  def destroy
    @pokemon_trainer.destroy
    respond_to do |format|
      format.html { redirect_to pokemon_trainers_url, notice: 'Pokemon trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon_trainer
      @pokemon_trainer = PokemonTrainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_trainer_params
      params.require(:pokemon_trainer).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_trainers_helper.rb
module PokemonTrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemon_trainers/_form.html.erb
<%= form_with(model: pokemon_trainer, local: true) do |form| %>
  <% if pokemon_trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon_trainer.errors.count, "error") %> prohibited this pokemon_trainer from being saved:</h2>

      <ul>
      <% pokemon_trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon_trainers/edit.html.erb
<h1>Editing Pokemon Trainer</h1>

<%= render 'form', pokemon_trainer: @pokemon_trainer %>

<%= link_to 'Show', @pokemon_trainer %> |
<%= link_to 'Back', pokemon_trainers_path %>

app/views/pokemon_trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemon Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon_trainers.each do |pokemon_trainer| %>
      <tr>
        <td><%= pokemon_trainer.name %></td>
        <td><%= link_to 'Show', pokemon_trainer %></td>
        <td><%= link_to 'Edit', edit_pokemon_trainer_path(pokemon_trainer) %></td>
        <td><%= link_to 'Destroy', pokemon_trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon Trainer', new_pokemon_trainer_path %>

app/views/pokemon_trainers/new.html.erb
<h1>New Pokemon Trainer</h1>

<%= render 'form', pokemon_trainer: @pokemon_trainer %>

<%= link_to 'Back', pokemon_trainers_path %>

app/views/pokemon_trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon_trainer.name %>
</p>

<%= link_to 'Edit', edit_pokemon_trainer_path(@pokemon_trainer) %> |
<%= link_to 'Back', pokemon_trainers_path %>